name: Auto Testing

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: development
      SECRET_KEY : secret_key
      ENCRYPT_KEY : plFSg-hzFkStMloooyfvsfioJPCSRw8lfY18hRLvU64=

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.4  # Adjust Python version if needed

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test
